USE GoodReadsDb

CREATE TRIGGER UpdateReviewDate
ON REVIEW
AFTER UPDATE
AS
BEGIN
   IF UPDATE(REVIEW_TEXT) OR UPDATE(RATING)
   BEGIN
      UPDATE REVIEW
	  SET REVIEW_DATE = GETDATE()
	  WHERE REVIEW_ID IN (SELECT REVIEW_ID FROM inserted);

	END
END

SELECT 
    B.BOOK_ID,
    B.TITLE AS BookTitle,
    B.PAGES AS NumberOfPages,
    B.PUBLICIAN_DATE AS PublicationDate,
    B.PUBLISHER AS Publisher,
    G.NAME AS Genre,
    A.FIRST_NAME + ' ' + A.LAST_NAME AS AuthorName,
    R.REVIEW_TEXT AS ReviewText,
    R.RATING AS Rating,
    R.REVIEW_DATE AS ReviewDate,
    U.USERNAME AS ReviewedBy
FROM 
    BOOK B
    JOIN GENRE G ON B.GENRE_ID = G.GENRE_ID
    JOIN AUTHOR A ON B.AUTHOR_ID = A.AUTHOR_ID
    LEFT JOIN REVIEW R ON B.BOOK_ID = R.BOOK_ID
    LEFT JOIN [USER] U ON R.USER_ID = U.USER_ID
SELECT 
    B.BOOK_ID,
    B.TITLE,
    R.REVIEW_TEXT,
    R.REVIEW_DATE,
	U.USER_ID,
	U.USERNAME
FROM
    REVIEW R
JOIN 
    BOOK B ON B.BOOK_ID = R.BOOK_ID
JOIN 
    [USER] U ON U.USER_ID = R.USER_ID;


	UPDATE REVIEW
	SET REVIEW_TEXT = 'Great'
	WHERE BOOK_ID = 9 AND USER_ID = 4
